#!/bin/bash

ln -sfT /dev/stdout /logs/storaged-stdout.log
ln -sfT /dev/stderr /logs/storaged-stderr.log

Array=()
if [ -n "${DEPEND_SERVICE-}" ]; then  
   metad_addr=$(nslookup "${DEPEND_SERVICE%:*}" | grep Address | sed '1d' | awk '{print $2}')
   for item in $metad_addr; do
      Array+=("$item":9559)
   done
fi
MetaServerAddrs=$(echo "${Array[@]}" | tr ' ' ',')
LocalIP=$(hostname -i)

/usr/local/nebula/bin/nebula-storaged \
--flagfile=/usr/local/nebula/etc/nebula-storaged.conf \
--meta_server_addrs="$MetaServerAddrs" \
--local_ip="$LocalIP" \
--ws_ip="$LocalIP" \
--daemonize=false