#!/bin/bash

ln -sfT /dev/stdout /usr/local/nebula/logs/graphd-stdout.log
ln -sfT /dev/stderr /usr/local/nebula/logs/graphd-stderr.log

if [ -n "${DEPEND_SERVICE}" ]; then  
   metad_fqdn=$(nslookup "${DEPEND_SERVICE%:*}" | grep Name | sed '1d' | awk '{print $2}' | sed -n 1p)
   metad_server_name=${metad_fqdn%%.*}
fi

/usr/local/nebula/bin/nebula-graphd \
--flagfile=/usr/local/nebula/etc/nebula-graphd.conf \
--meta_server_addrs="$metad_server_name"-0."$metad_fqdn":9559,"$metad_server_name"-1."$metad_fqdn":9559,"$metad_server_name"-2."$metad_fqdn":9559 \
--local_ip="$(hostname)"."$SERVICE_NAME"."$NAMESPACE".svc.cluster.local \
--ws_ip="$(hostname)"."$SERVICE_NAME"."$NAMESPACE".svc.cluster.local \
--daemonize=false